[connections.postgresql]
dialect = "postgresql"
host = "dev-prod-bridge.cj6yymi0wmxz.ap-south-1.rds.amazonaws.com"
port = 5432
database = "postgres"
username = "postgres"
password = "gr2hSgNpm0XelijN"

[data_dictionary]
sheet_url = "https://docs.google.com/spreadsheets/d/10548zsuon8GiOMbvVKk_JbOMtE6J2pmbHgmMA-RXa5s/edit?usp=sharing"

